export const RESET = "LUNCH_UPDATE_RESET";
export const SET_ERROR = "LUNCH_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "LUNCH_UPDATE_SET_RETRIEVED";
export const SET_HUB_URL = "LUNCH_UPDATE_SET_HUB_URL";
export const SET_UPDATED = "LUNCH_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "LUNCH_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "LUNCH_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "LUNCH_UPDATE_UPDATE_RETRIEVED";
