export const LUNCH_SHOW_RESET = "LUNCH_SHOW_RESET";
export const LUNCH_SHOW_SET_ERROR = "LUNCH_SHOW_SET_ERROR";
export const LUNCH_SHOW_SET_RETRIEVED = "LUNCH_SHOW_SET_RETRIEVED";
export const LUNCH_SHOW_SET_HUB_URL = "LUNCH_SHOW_SET_HUB_URL";
export const LUNCH_SHOW_TOGGLE_LOADING = "LUNCH_SHOW_TOGGLE_LOADING";
