export const LUNCH_DELETE_RESET = "LUNCH_DELETE_RESET";
export const LUNCH_DELETE_SET_ERROR = "LUNCH_DELETE_SET_ERROR";
export const LUNCH_DELETE_SET_DELETED = "LUNCH_DELETE_SET_DELETED";
export const LUNCH_DELETE_MERCURE_SET_DELETED =
  "LUNCH_DELETE_MERCURE_SET_DELETED";
export const LUNCH_DELETE_TOGGLE_LOADING = "LUNCH_DELETE_TOGGLE_LOADING";
