export const LUNCH_CREATE_RESET = "LUNCH_CREATE_RESET";
export const LUNCH_CREATE_SET_CREATED = "LUNCH_CREATE_SET_CREATED";
export const LUNCH_CREATE_SET_ERROR = "LUNCH_CREATE_SET_ERROR";
export const LUNCH_CREATE_SET_VIOLATIONS = "LUNCH_CREATE_SET_VIOLATIONS";
export const LUNCH_CREATE_TOGGLE_LOADING = "LUNCH_CREATE_TOGGLE_LOADING";
